"""oracle application baseline

Revision ID: 5fbab72fd965
Revises: 
Create Date: 2026-07-15 09:47:26.740382

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fbab72fd965'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invocation_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedback_invocation_id'), 'ai_feedback', ['invocation_id'], unique=False)
    op.create_table('ai_invocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('token_usage_input', sa.Integer(), nullable=True),
    sa.Column('token_usage_output', sa.Integer(), nullable=True),
    sa.Column('token_usage_total', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('output_schema_valid', sa.Boolean(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('edited', sa.Boolean(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('invoked_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_name'), 'api_tokens', ['name'], unique=False)
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_tokens_token_prefix'), 'api_tokens', ['token_prefix'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_name', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('source_ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('before', sa.Text(), nullable=True),
    sa.Column('after', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_name'), 'audit_logs', ['actor_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('call_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('assertion_results', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('pre_request_results', sa.Text(), nullable=True),
    sa.Column('has_files', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=True),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_history_method'), 'call_history', ['method'], unique=False)
    op.create_index(op.f('ix_call_history_status'), 'call_history', ['status'], unique=False)
    op.create_table('contract_diffs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('from_version', sa.Integer(), nullable=False),
    sa.Column('to_version', sa.Integer(), nullable=False),
    sa.Column('breaking_changes', sa.Text(), nullable=True),
    sa.Column('non_breaking_changes', sa.Text(), nullable=True),
    sa.Column('affected_test_cases', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_diffs_contract_id'), 'contract_diffs', ['contract_id'], unique=False)
    op.create_table('contract_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('openapi_spec', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_versions_contract_id'), 'contract_versions', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_versions_project_id'), 'contract_versions', ['project_id'], unique=False)
    op.create_table('defect_tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('external_system', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('test_result_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defect_tickets_project_id'), 'defect_tickets', ['project_id'], unique=False)
    op.create_table('environments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('variables', sa.Text(), nullable=False),
    sa.Column('db_config', sa.Text(), nullable=True),
    sa.Column('cookies', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_name'), 'environments', ['name'], unique=False)
    op.create_table('mock_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_headers', sa.Text(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('delay_ms', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('response_template', sa.Text(), nullable=True),
    sa.Column('match_rules', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('stateful_config', sa.Text(), nullable=True),
    sa.Column('fault_injection', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_configs_path'), 'mock_configs', ['path'], unique=False)
    op.create_table('notification_channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('webhook_url', sa.Text(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_channels_name'), 'notification_channels', ['name'], unique=False)
    op.create_index(op.f('ix_notification_channels_type'), 'notification_channels', ['type'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('quality_gate_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gate_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_gate_results_gate_id'), 'quality_gate_results', ['gate_id'], unique=False)
    op.create_table('quality_gates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_gates_project_id'), 'quality_gates', ['project_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('ui_locators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('selector_type', sa.String(length=30), nullable=False),
    sa.Column('selector_value', sa.String(length=500), nullable=False),
    sa.Column('alternative_selectors', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ui_locators_name'), 'ui_locators', ['name'], unique=False)
    op.create_index(op.f('ix_ui_locators_project_id'), 'ui_locators', ['project_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('webhook_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('events', sa.Text(), nullable=False),
    sa.Column('secret', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_configs_name'), 'webhook_configs', ['name'], unique=False)
    op.create_table('workflow_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('nodes', sa.Text(), nullable=True),
    sa.Column('edges', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_project_id'), 'workflow_definitions', ['project_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('node_results', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    op.create_table('defect_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('pattern_type', sa.String(length=32), nullable=False),
    sa.Column('related_interface', sa.String(length=2048), nullable=True),
    sa.Column('related_case_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ai_analysis_snapshot', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defect_patterns_pattern_type'), 'defect_patterns', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_defect_patterns_project_id'), 'defect_patterns', ['project_id'], unique=False)
    op.create_index(op.f('ix_defect_patterns_title'), 'defect_patterns', ['title'], unique=False)
    op.create_table('execution_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('assigned_worker_id', sa.String(length=64), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('request_snapshot', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by', 'idempotency_key', name='uq_execution_jobs_creator_idempotency')
    )
    op.create_index(op.f('ix_execution_jobs_job_type'), 'execution_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_execution_jobs_project_id'), 'execution_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_execution_jobs_resource_id'), 'execution_jobs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_execution_jobs_status'), 'execution_jobs', ['status'], unique=False)
    op.create_table('global_variables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('var_type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_variables_name'), 'global_variables', ['name'], unique=False)
    op.create_index(op.f('ix_global_variables_project_id'), 'global_variables', ['project_id'], unique=False)
    op.create_index(op.f('ix_global_variables_scope'), 'global_variables', ['scope'], unique=False)
    op.create_table('interface_knowledge',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('interface_path', sa.String(length=2048), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('field_meanings', sa.Text(), nullable=True),
    sa.Column('dependencies', sa.Text(), nullable=True),
    sa.Column('common_headers', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interface_knowledge_interface_path'), 'interface_knowledge', ['interface_path'], unique=False)
    op.create_index(op.f('ix_interface_knowledge_project_id'), 'interface_knowledge', ['project_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=True),
    sa.Column('channel_name', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_channel_id'), 'notification_logs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_created_at'), 'notification_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_logs_event_type'), 'notification_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_notification_logs_status'), 'notification_logs', ['status'], unique=False)
    op.create_table('notification_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_rules_channel_id'), 'notification_rules', ['channel_id'], unique=False)
    op.create_index(op.f('ix_notification_rules_event_type'), 'notification_rules', ['event_type'], unique=False)
    op.create_table('performance_tests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('case_ids', sa.Text(), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_tests_name'), 'performance_tests', ['name'], unique=False)
    op.create_index(op.f('ix_performance_tests_project_id'), 'performance_tests', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members_project_user')
    )
    op.create_index(op.f('ix_project_members_role'), 'project_members', ['role'], unique=False)
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('schedule_config', sa.String(length=256), nullable=False),
    sa.Column('case_ids', sa.Text(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step_library',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_library_name'), 'step_library', ['name'], unique=False)
    op.create_index(op.f('ix_step_library_project_id'), 'step_library', ['project_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group_path', sa.String(length=256), nullable=True),
    sa.Column('markers', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('headers', sa.Text(), nullable=False),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('graphql_query', sa.Text(), nullable=True),
    sa.Column('files', sa.Text(), nullable=True),
    sa.Column('extract_rules', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('retry_interval', sa.Float(), nullable=False),
    sa.Column('pre_script', sa.Text(), nullable=True),
    sa.Column('post_script', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('case_status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('parent_case_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_case_status'), 'test_cases', ['case_status'], unique=False)
    op.create_index(op.f('ix_test_cases_parent_case_id'), 'test_cases', ['parent_case_id'], unique=False)
    op.create_index(op.f('ix_test_cases_project_id'), 'test_cases', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_cases_sort_order'), 'test_cases', ['sort_order'], unique=False)
    op.create_index(op.f('ix_test_cases_title'), 'test_cases', ['title'], unique=False)
    op.create_table('test_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('environment_id', sa.String(length=36), nullable=True),
    sa.Column('execution_mode', sa.String(length=16), nullable=False),
    sa.Column('marker_filter', sa.String(length=64), nullable=True),
    sa.Column('stress_config', sa.Text(), nullable=True),
    sa.Column('scenario_type', sa.String(length=16), nullable=False),
    sa.Column('fail_strategy', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_plans_name'), 'test_plans', ['name'], unique=False)
    op.create_table('test_run_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('triggered_by', sa.String(length=128), nullable=True),
    sa.Column('scheduled_task_id', sa.String(length=36), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_run_summaries_run_id'), 'test_run_summaries', ['run_id'], unique=True)
    op.create_table('ui_elements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('selector_type', sa.String(length=32), nullable=False),
    sa.Column('selector_value', sa.String(length=512), nullable=False),
    sa.Column('page_url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ui_elements_name'), 'ui_elements', ['name'], unique=False)
    op.create_index(op.f('ix_ui_elements_project_id'), 'ui_elements', ['project_id'], unique=False)
    op.create_table('ui_test_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('browser_type', sa.String(length=32), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('retry_interval', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ui_test_cases_project_id'), 'ui_test_cases', ['project_id'], unique=False)
    op.create_index(op.f('ix_ui_test_cases_title'), 'ui_test_cases', ['title'], unique=False)
    op.create_table('ui_test_suites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('case_ids', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('max_workers', sa.Integer(), nullable=False),
    sa.Column('retry_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ui_test_suites_name'), 'ui_test_suites', ['name'], unique=False)
    op.create_index(op.f('ix_ui_test_suites_project_id'), 'ui_test_suites', ['project_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('assertion_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('assertion_type', sa.String(length=32), nullable=False),
    sa.Column('expression', sa.Text(), nullable=True),
    sa.Column('operator', sa.String(length=16), nullable=False),
    sa.Column('expected', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=4), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assertion_rules_test_case_id'), 'assertion_rules', ['test_case_id'], unique=False)
    op.create_table('business_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('module', sa.String(length=128), nullable=True),
    sa.Column('related_defect_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_defect_id'], ['defect_patterns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_rules_project_id'), 'business_rules', ['project_id'], unique=False)
    op.create_index(op.f('ix_business_rules_rule_type'), 'business_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_business_rules_title'), 'business_rules', ['title'], unique=False)
    op.create_table('db_assertions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sql_template', sa.Text(), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_assertions_test_case_id'), 'db_assertions', ['test_case_id'], unique=False)
    op.create_table('execution_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['execution_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_attempts_job_id'), 'execution_attempts', ['job_id'], unique=False)
    op.create_table('interface_change_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('before', sa.Text(), nullable=True),
    sa.Column('after', sa.Text(), nullable=True),
    sa.Column('changed_fields', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interface_change_logs_test_case_id'), 'interface_change_logs', ['test_case_id'], unique=False)
    op.create_table('job_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['execution_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_artifacts_job_id'), 'job_artifacts', ['job_id'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['execution_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_event_type'), 'job_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('performance_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('success_requests', sa.Integer(), nullable=False),
    sa.Column('fail_requests', sa.Integer(), nullable=False),
    sa.Column('avg_response_time', sa.Float(), nullable=False),
    sa.Column('min_response_time', sa.Float(), nullable=False),
    sa.Column('max_response_time', sa.Float(), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('p90', sa.Float(), nullable=False),
    sa.Column('p95', sa.Float(), nullable=False),
    sa.Column('p99', sa.Float(), nullable=False),
    sa.Column('rps', sa.Float(), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('sla_status', sa.String(length=16), nullable=True),
    sa.Column('sla_details', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['performance_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_results_run_id'), 'performance_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_performance_results_test_id'), 'performance_results', ['test_id'], unique=False)
    op.create_table('test_data_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('variables', sa.Text(), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_data_sets_name'), 'test_data_sets', ['name'], unique=False)
    op.create_index(op.f('ix_test_data_sets_test_case_id'), 'test_data_sets', ['test_case_id'], unique=False)
    op.create_table('test_plan_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['test_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_plan_items_plan_id'), 'test_plan_items', ['plan_id'], unique=False)
    op.create_index(op.f('ix_test_plan_items_test_case_id'), 'test_plan_items', ['test_case_id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('test_plan_id', sa.String(length=36), nullable=True),
    sa.Column('environment_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('request_snapshot', sa.Text(), nullable=True),
    sa.Column('response_snapshot', sa.Text(), nullable=True),
    sa.Column('assertion_results', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('trace_path', sa.String(length=512), nullable=True),
    sa.Column('screenshot_path', sa.String(length=512), nullable=True),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_run_id'), 'test_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_test_results_status'), 'test_results', ['status'], unique=False)
    op.create_index(op.f('ix_test_results_test_case_id'), 'test_results', ['test_case_id'], unique=False)
    op.create_table('ui_test_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('case_title', sa.String(length=256), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('browser_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('passed_steps', sa.Integer(), nullable=False),
    sa.Column('failed_steps', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('step_results', sa.Text(), nullable=True),
    sa.Column('retry_attempts', sa.Text(), nullable=False),
    sa.Column('final_attempt', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(length=128), nullable=False),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['ui_test_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ui_test_records_case_id'), 'ui_test_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_ui_test_records_executed_at'), 'ui_test_records', ['executed_at'], unique=False)
    op.create_index(op.f('ix_ui_test_records_project_id'), 'ui_test_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_ui_test_records_status'), 'ui_test_records', ['status'], unique=False)
    op.create_table('ui_test_suite_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('suite_id', sa.String(length=36), nullable=False),
    sa.Column('suite_name', sa.String(length=256), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('record_ids', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.String(length=128), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('max_workers', sa.Integer(), nullable=False),
    sa.Column('parallel_duration', sa.Float(), nullable=True),
    sa.Column('retry_enabled', sa.Boolean(), nullable=False),
    sa.Column('total_retries', sa.Integer(), nullable=False),
    sa.Column('retried_cases', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['suite_id'], ['ui_test_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ui_test_suite_runs_project_id'), 'ui_test_suite_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_ui_test_suite_runs_suite_id'), 'ui_test_suite_runs', ['suite_id'], unique=False)
    op.create_table('visual_baselines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ui_test_case_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('screenshot_path', sa.String(length=512), nullable=True),
    sa.Column('baseline_image', sa.Text(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ui_test_case_id'], ['ui_test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_baselines_ui_test_case_id'), 'visual_baselines', ['ui_test_case_id'], unique=False)
    op.create_table('perf_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=True),
    sa.Column('elapsed', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=False),
    sa.Column('memory', sa.Float(), nullable=False),
    sa.Column('disk_read', sa.Float(), nullable=False),
    sa.Column('disk_write', sa.Float(), nullable=False),
    sa.Column('net_sent', sa.Float(), nullable=False),
    sa.Column('net_recv', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['performance_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['performance_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perf_metrics_result_id'), 'perf_metrics', ['result_id'], unique=False)
    op.create_index(op.f('ix_perf_metrics_run_id'), 'perf_metrics', ['run_id'], unique=False)
    op.create_index(op.f('ix_perf_metrics_test_id'), 'perf_metrics', ['test_id'], unique=False)
    op.create_table('visual_diff_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ui_test_record_id', sa.String(length=36), nullable=False),
    sa.Column('baseline_id', sa.String(length=36), nullable=False),
    sa.Column('diff_score', sa.Float(), nullable=False),
    sa.Column('diff_image', sa.Text(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['visual_baselines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ui_test_record_id'], ['ui_test_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_diff_results_baseline_id'), 'visual_diff_results', ['baseline_id'], unique=False)
    op.create_index(op.f('ix_visual_diff_results_ui_test_record_id'), 'visual_diff_results', ['ui_test_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visual_diff_results_ui_test_record_id'), table_name='visual_diff_results')
    op.drop_index(op.f('ix_visual_diff_results_baseline_id'), table_name='visual_diff_results')
    op.drop_table('visual_diff_results')
    op.drop_index(op.f('ix_perf_metrics_test_id'), table_name='perf_metrics')
    op.drop_index(op.f('ix_perf_metrics_run_id'), table_name='perf_metrics')
    op.drop_index(op.f('ix_perf_metrics_result_id'), table_name='perf_metrics')
    op.drop_table('perf_metrics')
    op.drop_index(op.f('ix_visual_baselines_ui_test_case_id'), table_name='visual_baselines')
    op.drop_table('visual_baselines')
    op.drop_index(op.f('ix_ui_test_suite_runs_suite_id'), table_name='ui_test_suite_runs')
    op.drop_index(op.f('ix_ui_test_suite_runs_project_id'), table_name='ui_test_suite_runs')
    op.drop_table('ui_test_suite_runs')
    op.drop_index(op.f('ix_ui_test_records_status'), table_name='ui_test_records')
    op.drop_index(op.f('ix_ui_test_records_project_id'), table_name='ui_test_records')
    op.drop_index(op.f('ix_ui_test_records_executed_at'), table_name='ui_test_records')
    op.drop_index(op.f('ix_ui_test_records_case_id'), table_name='ui_test_records')
    op.drop_table('ui_test_records')
    op.drop_index(op.f('ix_test_results_test_case_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_status'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_run_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_test_plan_items_test_case_id'), table_name='test_plan_items')
    op.drop_index(op.f('ix_test_plan_items_plan_id'), table_name='test_plan_items')
    op.drop_table('test_plan_items')
    op.drop_index(op.f('ix_test_data_sets_test_case_id'), table_name='test_data_sets')
    op.drop_index(op.f('ix_test_data_sets_name'), table_name='test_data_sets')
    op.drop_table('test_data_sets')
    op.drop_index(op.f('ix_performance_results_test_id'), table_name='performance_results')
    op.drop_index(op.f('ix_performance_results_run_id'), table_name='performance_results')
    op.drop_table('performance_results')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_index(op.f('ix_job_events_event_type'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_job_artifacts_job_id'), table_name='job_artifacts')
    op.drop_table('job_artifacts')
    op.drop_index(op.f('ix_interface_change_logs_test_case_id'), table_name='interface_change_logs')
    op.drop_table('interface_change_logs')
    op.drop_index(op.f('ix_execution_attempts_job_id'), table_name='execution_attempts')
    op.drop_table('execution_attempts')
    op.drop_index(op.f('ix_db_assertions_test_case_id'), table_name='db_assertions')
    op.drop_table('db_assertions')
    op.drop_index(op.f('ix_business_rules_title'), table_name='business_rules')
    op.drop_index(op.f('ix_business_rules_rule_type'), table_name='business_rules')
    op.drop_index(op.f('ix_business_rules_project_id'), table_name='business_rules')
    op.drop_table('business_rules')
    op.drop_index(op.f('ix_assertion_rules_test_case_id'), table_name='assertion_rules')
    op.drop_table('assertion_rules')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_ui_test_suites_project_id'), table_name='ui_test_suites')
    op.drop_index(op.f('ix_ui_test_suites_name'), table_name='ui_test_suites')
    op.drop_table('ui_test_suites')
    op.drop_index(op.f('ix_ui_test_cases_title'), table_name='ui_test_cases')
    op.drop_index(op.f('ix_ui_test_cases_project_id'), table_name='ui_test_cases')
    op.drop_table('ui_test_cases')
    op.drop_index(op.f('ix_ui_elements_project_id'), table_name='ui_elements')
    op.drop_index(op.f('ix_ui_elements_name'), table_name='ui_elements')
    op.drop_table('ui_elements')
    op.drop_index(op.f('ix_test_run_summaries_run_id'), table_name='test_run_summaries')
    op.drop_table('test_run_summaries')
    op.drop_index(op.f('ix_test_plans_name'), table_name='test_plans')
    op.drop_table('test_plans')
    op.drop_index(op.f('ix_test_cases_title'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_sort_order'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_project_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_parent_case_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_case_status'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_step_library_project_id'), table_name='step_library')
    op.drop_index(op.f('ix_step_library_name'), table_name='step_library')
    op.drop_table('step_library')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_project_members_role'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_performance_tests_project_id'), table_name='performance_tests')
    op.drop_index(op.f('ix_performance_tests_name'), table_name='performance_tests')
    op.drop_table('performance_tests')
    op.drop_index(op.f('ix_notification_rules_event_type'), table_name='notification_rules')
    op.drop_index(op.f('ix_notification_rules_channel_id'), table_name='notification_rules')
    op.drop_table('notification_rules')
    op.drop_index(op.f('ix_notification_logs_status'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_event_type'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_created_at'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_channel_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_interface_knowledge_project_id'), table_name='interface_knowledge')
    op.drop_index(op.f('ix_interface_knowledge_interface_path'), table_name='interface_knowledge')
    op.drop_table('interface_knowledge')
    op.drop_index(op.f('ix_global_variables_scope'), table_name='global_variables')
    op.drop_index(op.f('ix_global_variables_project_id'), table_name='global_variables')
    op.drop_index(op.f('ix_global_variables_name'), table_name='global_variables')
    op.drop_table('global_variables')
    op.drop_index(op.f('ix_execution_jobs_status'), table_name='execution_jobs')
    op.drop_index(op.f('ix_execution_jobs_resource_id'), table_name='execution_jobs')
    op.drop_index(op.f('ix_execution_jobs_project_id'), table_name='execution_jobs')
    op.drop_index(op.f('ix_execution_jobs_job_type'), table_name='execution_jobs')
    op.drop_table('execution_jobs')
    op.drop_index(op.f('ix_defect_patterns_title'), table_name='defect_patterns')
    op.drop_index(op.f('ix_defect_patterns_project_id'), table_name='defect_patterns')
    op.drop_index(op.f('ix_defect_patterns_pattern_type'), table_name='defect_patterns')
    op.drop_table('defect_patterns')
    op.drop_index(op.f('ix_workflow_runs_workflow_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_workflow_definitions_project_id'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    op.drop_index(op.f('ix_webhook_configs_name'), table_name='webhook_configs')
    op.drop_table('webhook_configs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ui_locators_project_id'), table_name='ui_locators')
    op.drop_index(op.f('ix_ui_locators_name'), table_name='ui_locators')
    op.drop_table('ui_locators')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_quality_gates_project_id'), table_name='quality_gates')
    op.drop_table('quality_gates')
    op.drop_index(op.f('ix_quality_gate_results_gate_id'), table_name='quality_gate_results')
    op.drop_table('quality_gate_results')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notification_channels_type'), table_name='notification_channels')
    op.drop_index(op.f('ix_notification_channels_name'), table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index(op.f('ix_mock_configs_path'), table_name='mock_configs')
    op.drop_table('mock_configs')
    op.drop_index(op.f('ix_environments_name'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_defect_tickets_project_id'), table_name='defect_tickets')
    op.drop_table('defect_tickets')
    op.drop_index(op.f('ix_contract_versions_project_id'), table_name='contract_versions')
    op.drop_index(op.f('ix_contract_versions_contract_id'), table_name='contract_versions')
    op.drop_table('contract_versions')
    op.drop_index(op.f('ix_contract_diffs_contract_id'), table_name='contract_diffs')
    op.drop_table('contract_diffs')
    op.drop_index(op.f('ix_call_history_status'), table_name='call_history')
    op.drop_index(op.f('ix_call_history_method'), table_name='call_history')
    op.drop_table('call_history')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_project_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_tokens_token_prefix'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_name'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_table('ai_invocations')
    op.drop_index(op.f('ix_ai_feedback_invocation_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    # ### end Alembic commands ###
